# Generated by Django 5.2.7 on 2026-03-26 11:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "1076_add_ai_word_extraction"),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, help_text='Extracted text from all regions of this field, joined in reading order', verbose_name='value')),
                ('extracted_at', models.DateTimeField(auto_now_add=True, verbose_name='extracted at')),
            ],
            options={
                'verbose_name': 'document field value',
                'verbose_name_plural': 'document field values',
            },
        ),
        migrations.CreateModel(
            name='DocumentTypeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this template', max_length=128, verbose_name='name')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
            ],
            options={
                'verbose_name': 'document type template',
                'verbose_name_plural': 'document type templates',
            },
        ),
        migrations.CreateModel(
            name='DocumentTypeTemplateField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Field name, e.g. 'client_name', 'date', 'total'", max_length=128, verbose_name='name')),
                ('regions', models.JSONField(help_text="List of page regions for this field. Format: [{'page': 1, 'x0': 150, 'y0': 400, 'x1': 500, 'y1': 440}]", verbose_name='regions')),
            ],
            options={
                'verbose_name': 'document type template field',
                'verbose_name_plural': 'document type template fields',
            },
        ),
        migrations.RemoveConstraint(
            model_name='documentpage',
            name='documents_documentpage_unique_doc_page',
        ),
        migrations.RenameIndex(
            model_name='documentword',
            new_name='documents_d_page_id_d0e98f_idx',
            old_name='documents_d_page_id_word_idx',
        ),
        migrations.RenameIndex(
            model_name='documentword',
            new_name='documents_d_text_eaa50d_idx',
            old_name='documents_d_text_idx',
        ),
        migrations.RenameIndex(
            model_name='documentword',
            new_name='documents_d_confide_79cde8_idx',
            old_name='documents_d_confid_idx',
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentword',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentword',
            name='language',
            field=models.CharField(blank=True, help_text="Detected language code (e.g., 'en', 'de')", max_length=10, verbose_name='language'),
        ),
        migrations.AlterUniqueTogether(
            name='documentpage',
            unique_together={('document', 'page_number')},
        ),
        migrations.AddField(
            model_name='documentfieldvalue',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='documents.document', verbose_name='document'),
        ),
        migrations.AddField(
            model_name='documenttypetemplate',
            name='document_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='documents.documenttype', verbose_name='document type'),
        ),
        migrations.AddField(
            model_name='documenttypetemplatefield',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='documents.documenttypetemplate', verbose_name='template'),
        ),
        migrations.AddField(
            model_name='documentfieldvalue',
            name='template_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='documents.documenttypetemplatefield', verbose_name='template field'),
        ),
        migrations.AlterUniqueTogether(
            name='documenttypetemplatefield',
            unique_together={('template', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='documentfieldvalue',
            unique_together={('document', 'template_field')},
        ),
    ]
