# Generated by Django 5.2.7 on 2026-04-08 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1078_default_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttypetemplate',
            name='blank_document',
            field=models.ForeignKey(blank=True, help_text='The blank/empty form document used as the template base', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_blank_template', to='documents.document', verbose_name='blank document'),
        ),
    ]
